branch-defaults:
  main:
    environment: markett-production
    group_suffix: null
deploy:
  artifact: application.zip
global:
  application_name: Markett
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
